module "mcm_import" {
  source                     			= "git::https://github.com/IBM-CAMHub-Open/template_mcm_modules.git?ref=3.2.0//config_mcm_icp_import"
  import_launch_node_ip          		= "${var.import_launch_node_ip}"
  vm_os_user                 			= "${var.vm_os_user}"
  vm_os_password             			= "${var.vm_os_password}"
  vm_os_private_key             		= "${var.vm_os_private_key}"
  icp_server_url					    = "${var.cluster_server_host}"
  cluster_name            				= "${var.cluster_name}"    
  admin_user             				= "${var.admin_user}"
  admin_user_password           		= "${var.admin_user_password}"
  icp_inception_image					= "${var.icp_inception_image}"    
  icp_dir           			 		= "${var.icp_dir}"
  man_cluster_on_hub            		= "${var.man_cluster_on_hub}"
  cluster_docker_registry_server_name 	= "${var.cluster_docker_registry_server_name}"
  cluster_docker_registry_server_ip 	= "${var.cluster_docker_registry_server_ip}"
  cluster_docker_registry_server_port   = "${var.cluster_docker_registry_server_port}"       
  cluster_docker_registry_server_ca_crt = "${var.cluster_docker_registry_server_ca_crt}"  
  #######
  mcm_controller_server_name            = "${var.mcm_controller_server_name}" 
  mcm_controller_admin_user             = "${var.mcm_controller_admin_user}"
  mcm_controller_admin_user_password    = "${var.mcm_controller_admin_user_password}"
  #######
  #cluster_config						= "${var.cluster_config}"
  #cluster_certificate_authority			= "${var.cluster_certificate_authority}"
  #######
  bastion_host               = "${var.bastion_host}"
  bastion_user               = "${var.bastion_user}"
  bastion_private_key        = "${var.bastion_private_key}"
  bastion_port               = "${var.bastion_port}"
  bastion_host_key           = "${var.bastion_host_key}"
  bastion_password           = "${var.bastion_password}"  
}